#!/usr/bin/env bash
set -euo pipefail

KVER="${1:-$(uname -r)}"

KEY_DIR="${KEY_DIR:-/root/secureboot-keys}"
KEY_PRIV="$KEY_DIR/MOK.priv"
KEY_PEM="$KEY_DIR/MOK.pem"
KEY_DER="$KEY_DIR/MOK.der"

# Accepted signers for already-signed modules.
#
# "Local Secure Boot Kernel Signing":
#   Your enrolled MOK key, used by this script.
#
# "Build time autogenerated kernel key":
#   Common signer for in-tree modules built as part of the kernel package.
#
# Override if needed:
#   sudo ACCEPTED_SIGNERS="Signer A|Signer B" ./sign-kernel-and-all-modules.sh <kver>
ACCEPTED_SIGNERS="${ACCEPTED_SIGNERS:-Local Secure Boot Kernel Signing|Build time autogenerated kernel key}"

VMLINUX="/boot/vmlinuz-$KVER"
VMLINUX_UNSIGNED="/boot/vmlinuz-$KVER.unsigned"
KCONFIG="/boot/config-$KVER"
MODULE_ROOT="/lib/modules/$KVER"
SIGN_FILE="$MODULE_ROOT/build/scripts/sign-file"

HASH_ALGO="${HASH_ALGO:-sha256}"
DO_INITRAMFS="${DO_INITRAMFS:-1}"
DO_GRUB="${DO_GRUB:-1}"
REQUIRE_MOK_ENROLLED="${REQUIRE_MOK_ENROLLED:-1}"

LOG_FILE="/var/log/self-sign-kernel-${KVER}-$(date +%Y%m%d-%H%M%S).log"

SIGNED_COUNT=0
SKIPPED_ACCEPTED_COUNT=0
WARN_UNACCEPTED_SIGNER_COUNT=0
UNACCEPTED_AFTER_COUNT=0
UNSIGNED_AFTER_COUNT=0
VERMAGIC_MISMATCH_COUNT=0
ERROR_COUNT=0

usage() {
  cat <<USAGE_EOF
Usage:
  sudo $0 [kernel-version]

Example:
  sudo $0 7.1.0-070100rc7-generic

Expected key files:
  $KEY_PRIV
  $KEY_PEM
  $KEY_DER

Useful overrides:
  sudo KEY_DIR=/root/secureboot-keys $0 <kernel-version>

  sudo ACCEPTED_SIGNERS="Local Secure Boot Kernel Signing|Build time autogenerated kernel key" \\
    $0 <kernel-version>

  sudo DO_INITRAMFS=0 DO_GRUB=0 $0 <kernel-version>

  sudo REQUIRE_MOK_ENROLLED=0 $0 <kernel-version>
USAGE_EOF
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

warn() {
  echo "WARN: $*" >&2
}

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run as root, e.g. sudo $0 $KVER"
}

require_tool() {
  local tool="$1"
  command -v "$tool" >/dev/null 2>&1 || die "Missing tool: $tool"
}

require_file() {
  local path="$1"
  [[ -e "$path" ]] || die "Missing: $path"
}

require_exec() {
  local path="$1"
  [[ -x "$path" ]] || die "Missing executable: $path. Install matching kernel headers for $KVER."
}

find_has_match() {
  local root="$1"
  local pattern="$2"
  find "$root" -type f -name "$pattern" -print -quit | grep -q .
}

kernel_image_has_signature() {
  local image="$1"
  local output
  local status

  set +e
  output="$(sbverify --list "$image" 2>&1)"
  status=$?
  set -e

  # Typical unsigned output from sbverify:
  #   No signature table present
  if grep -qiE 'No signature table present|No signatures found|not signed' <<<"$output"; then
    return 1
  fi

  # Typical signed output includes lines like:
  #   signature 1
  #   image signature issuers:
  #   image signature certificates:
  if grep -qiE '^signature[[:space:]]+[0-9]+|image signature|signature certificates|signature issuers' <<<"$output"; then
    return 0
  fi

  # Some sbverify versions may return non-zero for unsigned images without using
  # the exact text above. Treat non-zero as unsigned only if the output does not
  # contain clear signed-image markers.
  if [[ "$status" -ne 0 ]]; then
    return 1
  fi

  die "Could not clearly determine signature state for kernel image: $image

sbverify exit status:
  $status

sbverify output:
$output

Refusing to guess. Please inspect manually:
  sudo sbverify --list $image"
}

module_has_signature() {
  local mod="$1"
  modinfo -F sig_id "$mod" 2>/dev/null | grep -q .
}

module_signer() {
  local mod="$1"
  modinfo -F signer "$mod" 2>/dev/null || true
}

module_vermagic() {
  local mod="$1"
  modinfo -F vermagic "$mod" 2>/dev/null || true
}

module_vermagic_matches_kernel() {
  local mod="$1"
  local vermagic
  vermagic="$(module_vermagic "$mod")"

  [[ -n "$vermagic" ]] || return 1

  # Typical vermagic:
  #   7.1.0-070100rc7-generic SMP preempt mod_unload modversions
  [[ "$vermagic" == "$KVER"* ]]
}

module_is_signed_by_accepted_key() {
  local mod="$1"
  local signer
  local accepted_signer

  signer="$(module_signer "$mod")"

  IFS='|' read -r -a accepted_signers <<< "$ACCEPTED_SIGNERS"

  for accepted_signer in "${accepted_signers[@]}"; do
    if [[ "$signer" == "$accepted_signer" ]]; then
      return 0
    fi
  done

  return 1
}

check_mok_enrolled() {
  if [[ "$REQUIRE_MOK_ENROLLED" != "1" ]]; then
    warn "Skipping MOK enrolment check because REQUIRE_MOK_ENROLLED=$REQUIRE_MOK_ENROLLED"
    return 0
  fi

  local output
  local status

  set +e
  output="$(mokutil --test-key "$KEY_DER" 2>&1)"
  status=$?
  set -e

  echo "MOK test output:"
  echo "$output"

  if grep -qiE 'already enrolled|is enrolled|key is already enrolled' <<<"$output"; then
    echo "MOK certificate appears to be enrolled."
    return 0
  fi

  if [[ "$status" -eq 0 ]]; then
    echo "MOK certificate check returned success."
    return 0
  fi

  die "MOK certificate does not appear to be enrolled: $KEY_DER

mokutil exit status:
  $status

mokutil output:
$output

Enrol it first with:
  sudo mokutil --import $KEY_DER
then reboot and complete MokManager enrolment."
}

check_kernel_config() {
  require_file "$KCONFIG"

  if ! grep -q '^CONFIG_MODULE_SIG=y' "$KCONFIG"; then
    die "Kernel config does not appear to have CONFIG_MODULE_SIG=y: $KCONFIG"
  fi

  if grep -q '^CONFIG_MODULE_SIG_FORCE=y' "$KCONFIG"; then
    echo "Kernel enforces signed modules: CONFIG_MODULE_SIG_FORCE=y"
  else
    echo "Kernel supports module signatures but may not enforce them by config alone."
    echo "Secure Boot lockdown may still reject unsigned modules at load time."
  fi
}

sign_kernel_image() {
  echo
  echo "== Kernel image =="
  echo "Target: $VMLINUX"

  require_file "$VMLINUX"

  if [[ -f "$VMLINUX_UNSIGNED" ]]; then
    echo "Using existing unsigned backup:"
    echo "  $VMLINUX_UNSIGNED"

    if kernel_image_has_signature "$VMLINUX_UNSIGNED"; then
      die "Unsigned backup already appears signed: $VMLINUX_UNSIGNED
Replace it with the original unsigned kernel image before rerunning."
    fi
  else
    if kernel_image_has_signature "$VMLINUX"; then
      die "Kernel image appears signed, but no unsigned backup exists: $VMLINUX_UNSIGNED
Refusing to re-sign an already-signed kernel image blindly.
Restore or provide the original unsigned vmlinuz as $VMLINUX_UNSIGNED, then rerun."
    fi

    echo "Creating unsigned backup from currently installed unsigned kernel image:"
    echo "  $VMLINUX_UNSIGNED"
    cp -a "$VMLINUX" "$VMLINUX_UNSIGNED"
  fi

  local tmp_signed
  tmp_signed="$(mktemp "/boot/vmlinuz-${KVER}.signed.XXXXXX")"

  echo "Signing kernel image with sbsign..."
  sbsign \
    --key "$KEY_PRIV" \
    --cert "$KEY_PEM" \
    --output "$tmp_signed" \
    "$VMLINUX_UNSIGNED"

  chmod --reference="$VMLINUX_UNSIGNED" "$tmp_signed"
  chown --reference="$VMLINUX_UNSIGNED" "$tmp_signed"
  mv "$tmp_signed" "$VMLINUX"

  echo "Kernel image signature:"
  sbverify --list "$VMLINUX" || true
}

handle_signed_module() {
  local mod="$1"

  if module_is_signed_by_accepted_key "$mod"; then
    echo "SKIP already signed by accepted key: $mod"
    echo "  signer: $(module_signer "$mod")"
    SKIPPED_ACCEPTED_COUNT=$((SKIPPED_ACCEPTED_COUNT + 1))
  else
    echo "WARN signed by an unaccepted key, not re-signing in-place: $mod"
    echo "  signer: $(module_signer "$mod")"
    WARN_UNACCEPTED_SIGNER_COUNT=$((WARN_UNACCEPTED_SIGNER_COUNT + 1))
  fi
}

precheck_module_scope() {
  local mod="$1"

  if ! module_vermagic_matches_kernel "$mod"; then
    echo "SKIP vermagic mismatch: $mod"
    echo "  vermagic: $(module_vermagic "$mod")"
    VERMAGIC_MISMATCH_COUNT=$((VERMAGIC_MISMATCH_COUNT + 1))
    return 1
  fi

  return 0
}

sign_uncompressed_module() {
  local mod="$1"

  precheck_module_scope "$mod" || return 0

  if module_has_signature "$mod"; then
    handle_signed_module "$mod"
    return 0
  fi

  echo "SIGN module: $mod"
  "$SIGN_FILE" "$HASH_ALGO" "$KEY_PRIV" "$KEY_DER" "$mod"
  SIGNED_COUNT=$((SIGNED_COUNT + 1))
}

sign_compressed_module() {
  local mod="$1"
  local compression="$2"

  precheck_module_scope "$mod" || return 0

  if module_has_signature "$mod"; then
    handle_signed_module "$mod"
    return 0
  fi

  local uid gid mode
  uid="$(stat -c '%u' "$mod")"
  gid="$(stat -c '%g' "$mod")"
  mode="$(stat -c '%a' "$mod")"

  local tmpdir tmp_ko tmp_compressed
  tmpdir="$(mktemp -d)"
  tmp_ko="$tmpdir/$(basename "$mod")"
  tmp_ko="${tmp_ko%.zst}"
  tmp_ko="${tmp_ko%.xz}"
  tmp_ko="${tmp_ko%.gz}"
  tmp_compressed="$tmpdir/$(basename "$mod")"

  echo "SIGN compressed module: $mod"

  case "$compression" in
    zst)
      zstd -q -dc "$mod" > "$tmp_ko"
      ;;
    xz)
      xz -dc "$mod" > "$tmp_ko"
      ;;
    gz)
      gzip -dc "$mod" > "$tmp_ko"
      ;;
    *)
      rm -rf "$tmpdir"
      die "Unsupported compression: $compression for $mod"
      ;;
  esac

  "$SIGN_FILE" "$HASH_ALGO" "$KEY_PRIV" "$KEY_DER" "$tmp_ko"

  case "$compression" in
    zst)
      zstd -q -f -o "$tmp_compressed" "$tmp_ko"
      ;;
    xz)
      xz -c "$tmp_ko" > "$tmp_compressed"
      ;;
    gz)
      gzip -c "$tmp_ko" > "$tmp_compressed"
      ;;
  esac

  install -m "$mode" "$tmp_compressed" "$mod"
  chown "$uid:$gid" "$mod"

  rm -rf "$tmpdir"
  SIGNED_COUNT=$((SIGNED_COUNT + 1))
}

sign_all_matching_modules() {
  echo
  echo "== Kernel modules =="
  echo "Root: $MODULE_ROOT"
  echo "Policy: sign every unsigned .ko/.ko.zst/.ko.xz/.ko.gz whose vermagic starts with:"
  echo "  $KVER"
  echo "Accepted signers for already-signed modules:"
  echo "  $ACCEPTED_SIGNERS"
  echo

  local total=0

  while IFS= read -r -d '' mod; do
    total=$((total + 1))

    case "$mod" in
      *.ko)
        sign_uncompressed_module "$mod"
        ;;
      *.ko.zst)
        sign_compressed_module "$mod" "zst"
        ;;
      *.ko.xz)
        sign_compressed_module "$mod" "xz"
        ;;
      *.ko.gz)
        sign_compressed_module "$mod" "gz"
        ;;
      *)
        echo "SKIP unknown module format: $mod"
        ;;
    esac
  done < <(
    find "$MODULE_ROOT" -type f \
      \( -name '*.ko' -o -name '*.ko.zst' -o -name '*.ko.xz' -o -name '*.ko.gz' \) \
      -print0
  )

  echo
  echo "Scanned module files: $total"
}

refresh_boot_artifacts() {
  echo
  echo "== Refreshing boot artifacts =="

  echo "Running depmod..."
  depmod -a "$KVER"

  if [[ "$DO_INITRAMFS" == "1" ]]; then
    echo "Updating initramfs for $KVER..."
    update-initramfs -u -k "$KVER"
  else
    echo "Skipping initramfs update because DO_INITRAMFS=$DO_INITRAMFS"
  fi

  if [[ "$DO_GRUB" == "1" ]]; then
    echo "Updating GRUB..."
    update-grub
  else
    echo "Skipping GRUB update because DO_GRUB=$DO_GRUB"
  fi
}

verify_summary() {
  echo
  echo "== Verification summary =="

  echo "Kernel image:"
  sbverify --list "$VMLINUX" || true

  echo
  echo "Checking matching modules after signing..."

  while IFS= read -r -d '' mod; do
    if ! module_vermagic_matches_kernel "$mod"; then
      continue
    fi

    if ! module_has_signature "$mod"; then
      echo "UNSIGNED: $mod"
      echo "  vermagic: $(module_vermagic "$mod")"
      UNSIGNED_AFTER_COUNT=$((UNSIGNED_AFTER_COUNT + 1))
      continue
    fi

    if ! module_is_signed_by_accepted_key "$mod"; then
      echo "SIGNED-BY-UNACCEPTED-KEY: $mod"
      echo "  signer: $(module_signer "$mod")"
      UNACCEPTED_AFTER_COUNT=$((UNACCEPTED_AFTER_COUNT + 1))
    fi
  done < <(
    find "$MODULE_ROOT" -type f \
      \( -name '*.ko' -o -name '*.ko.zst' -o -name '*.ko.xz' -o -name '*.ko.gz' \) \
      -print0
  )

  echo
  echo "Counts:"
  echo "  newly signed modules:                    $SIGNED_COUNT"
  echo "  already signed by accepted key:          $SKIPPED_ACCEPTED_COUNT"
  echo "  signed by unaccepted key, not modified:  $WARN_UNACCEPTED_SIGNER_COUNT"
  echo "  unaccepted signer after verification:    $UNACCEPTED_AFTER_COUNT"
  echo "  skipped due to vermagic mismatch:        $VERMAGIC_MISMATCH_COUNT"
  echo "  unsigned matching modules after run:     $UNSIGNED_AFTER_COUNT"

  if [[ "$WARN_UNACCEPTED_SIGNER_COUNT" -gt 0 || "$UNACCEPTED_AFTER_COUNT" -gt 0 ]]; then
    echo
    warn "Some matching modules were already signed by an unaccepted key."
    warn "The script did not re-sign them in-place. Confirm that those signer keys are trusted before relying on this kernel."
  fi

  if [[ "$UNSIGNED_AFTER_COUNT" -gt 0 ]]; then
    echo
    warn "Some matching modules are still unsigned after the run. Review the log before rebooting into this kernel."
    ERROR_COUNT=$((ERROR_COUNT + 1))
  fi

  echo
  echo "Log file:"
  echo "  $LOG_FILE"
}

main() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
  fi

  require_root

  mkdir -p "$(dirname "$LOG_FILE")"
  exec > >(tee -a "$LOG_FILE") 2>&1

  echo "Self-signing kernel and modules"
  echo "Started: $(date -Is)"
  echo "Kernel version: $KVER"
  echo "Accepted module signers: $ACCEPTED_SIGNERS"

  require_tool sbsign
  require_tool sbverify
  require_tool mokutil
  require_tool modinfo
  require_tool depmod
  require_tool find
  require_tool grep
  require_tool stat
  require_tool install
  require_tool update-initramfs
  require_tool update-grub

  require_file "$KEY_PRIV"
  require_file "$KEY_PEM"
  require_file "$KEY_DER"
  require_file "$VMLINUX"
  require_file "$MODULE_ROOT"
  require_exec "$SIGN_FILE"

  check_mok_enrolled
  check_kernel_config

  if find_has_match "$MODULE_ROOT" '*.ko.zst'; then
    require_tool zstd
  fi

  if find_has_match "$MODULE_ROOT" '*.ko.xz'; then
    require_tool xz
  fi

  if find_has_match "$MODULE_ROOT" '*.ko.gz'; then
    require_tool gzip
  fi

  sign_kernel_image
  sign_all_matching_modules
  refresh_boot_artifacts
  verify_summary

  echo
  if [[ "$ERROR_COUNT" -gt 0 ]]; then
    die "Completed with errors/warnings that require review. See: $LOG_FILE"
  fi

  echo "Done."
  echo "Reboot, then verify with:"
  echo "  mokutil --sb-state"
  echo "  uname -r"
  echo "  journalctl -k -b | grep -Ei 'signature|module verification|required key|lockdown'"
}

main "$@"